[bumpver]
current_version = "1.0.0"
version_pattern = "MAJOR.MINOR.PATCH"
commit = false       # We do version bumping in CI, not as a commit
tag = false          # Git tag already exists — we don't auto-tag
push = false         # Don't push anything in CI

# Optional: define which files to update
# bumpver will look for `{version}` in these files
files = [
    "setup.cfg",
    "src/unicorn_eval/__init__.py",
]
