name: PR tests for adaptors

on:
  pull_request:
    types: [opened, synchronize, reopened]
    workflow_dispatch:  # allows manual run from GitHub ui

jobs:
  docker-test:
    runs-on: ubuntu-latest
    timeout-minutes: 60 # should complete in 1h
    permissions:
      contents: read

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Verify required folders exist
        run: |
          set -euo pipefail
          test -d tests/adaptors/image-level/input
          test -d tests/adaptors/image-level/ground_truth

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          load: true
          tags: unicorn-eval:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run container entrypoint
        shell: bash
        run: |
          set -euo pipefail
          docker run --rm \
            -v "$GITHUB_WORKSPACE/tests/adaptors/input:/input" \
            -v "$GITHUB_WORKSPACE/tests/adaptors/ground_truth:/opt/ml/input/data/ground_truth" \
            unicorn-eval:${{ github.sha }}